### ISSUE TITLE
Correzione esercizi.

### ISSUE THREAD

**Issue by spinafranci** [strumet/strumet.github.io#243]
Buonasera Marco,
a seguito della sua ultima revisione ho notato che i miei esercizi (rif. a CAD 01, RASTER 00, VECTOR 05) non sono stati di nuovo accettati. Controllando su git hub, ho notato che il mio cad 01 corretto, pur essendo stato caricato, non viene visualizzato. Mi sa dire come posso fargli avere i file corretti?

**Comment by spinafranci** [comment]
Per quanto riguarda il raster e vector, non so quale sia il problema in quanto lo avevo corretto. mi sa dire cosa devo correggere di nuovo?
grazie!

**Comment by strumet** [comment]
Ciao Francesca,
come è possibile vedere dal tuo profilo github (vedi immagine allegata) per gli ultimi tuoi commit **non è stata effettuato il pull request** ("_This branch is 2 commits ahead_"): non ho avuto pertanto la possibilità di vedere le ultime versioni dei tuoi esercizi.

![control](https://user-images.githubusercontent.com/6952124/42073949-c7c289f4-7b69-11e8-8846-253163314d54.png)

Effettua, quindi, il pull request e provvederò ad aggiungere i tuoi file al repository del corso per revisionarli alla prossima occasione (la prossima revisione degli esercizi dovrei farla lunedì).

È utile ricordare, infine, che tutto il sistema di consegne e revisioni è stato pensato proprio per darvi modo di verificare voi stessi i file ricevuti, gli esercizi accettati, le date delle operazioni, etc... (ad esempio, [cliccando sul tasto "_Compare_"](https://github.com/strumet/strumet.github.io/compare/master...spinafranci:master) del tuo repository remoto puoi vedere quali file hai caricato sul tuo repository ma non sono ancora presenti nel repository del corso).

Un saluto,
mf

**Comment by spinafranci** [comment]
Ok. Ho fatto pull request! Grazie mille
