### ISSUE TITLE
Domanda Vectors

### ISSUE THREAD

**Issue by camilladeamicis** [strumet/strumet.github.io#246]
Buongiorno, 
ho controllato la nuova revisione degli esercizi, sono a posto cad e raster, purtroppo però gli es 02 e dallo 06 in poi dei vectors non sono stati accettati. Avevo ricaricato lo 02 che avevo corretto in classe e poi lasciato da accettare dallo 06 in poi che avevo già corretto in precedenza, li avevamo guardati insieme in classe aprendo gli svg sul browser. La mia matricola è 890725, non capisco perchè non vengano accettati dal momento che li avevamo rivisti in classe e li avevo corretti. Grazie mi scusi il continuo disturbo, Camilla De Amicis, un saluto.

**Comment by strumet** [comment]
Ciao Camilla,
grazie per la segnalazione.
Effettivamente durante la revisione il tuo esercizio EX06 deve essermi sfuggito e, di conseguenza, i successivi. Scusami, può capitare. Da un'occhiata veloce posso dire che sembrano corretti, quindi, con la prossima revisione saranno, molto probabilmente, accettati.
Nella tavola realizzata per l'esercizio EX02, invece, non è presente l'immagine incorporata (embedded) [richiesta dal testo dell'esercizio](https://github.com/strumet/strumet.github.io/tree/master/ex/vectors#ex02) (è, invece, presente un'immagine linkata).
